import { useLocalDay } from '@/src/ui/useLocalDay';
import { getReminderDate } from '@/src/notifications/reminderDate';
import { shiftCalendarMonth } from '@/src/ui/calendarPresentation';
import { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import * as Haptics from 'expo-haptics';
import { NeverScreen } from '@/src/ui/NeverScreen';
import { useItems } from '@/src/context/ItemsContext';
import { OneIcon, icons } from '@/src/ui/icons';
import { V5Chevron, V5Segmented, useNeverV5Palette } from '@/src/ui/appleV5';
import { Pass3Divider, Pass3Section, Pass3TextAction } from '@/src/ui/pass3/Pass3Section';
import { Pass3ScreenIntro } from '@/src/ui/pass3/Pass3ScreenIntro';
import type { OneItem } from '@/src/types/item';

type CalendarMode='Day'|'Week'|'Month';

export default function CalendarV5(){
 const p=useNeverV5Palette();const{items}=useItems();const today=useLocalDay();const[chosenDate,setSelectedDate]=useState<string|null>(null);const selectedDate=chosenDate??today;const[mode,setMode]=useState<CalendarMode>('Day');
 const datedItems=useMemo(()=>items.filter((item)=>getReminderDate({date:item.date},0)&&!item.completed).sort((a,b)=>`${a.date}T${a.time||'23:59'}`.localeCompare(`${b.date}T${b.time||'23:59'}`)),[items]);
 const selected=new Date(`${selectedDate}T12:00:00`);const strip=getDays(selected,7);const selectedItems=useMemo(()=>datedItems.filter((item)=>item.date===selectedDate),[datedItems,selectedDate]);const nextDate=useMemo(()=>addDaysIso(selectedDate,1),[selectedDate]);const nextItems=useMemo(()=>datedItems.filter((item)=>item.date===nextDate),[datedItems,nextDate]);const visibleItems=useMemo(()=>filterForMode(datedItems,selectedDate,mode),[datedItems,selectedDate,mode]);const grouped=useMemo(()=>groupByDate(visibleItems),[visibleItems]);const monthName=new Intl.DateTimeFormat('en',{month:'long'}).format(selected);const weekdayName=new Intl.DateTimeFormat('en',{weekday:'long'}).format(selected);
 async function moveMonth(delta:number){void Haptics.selectionAsync().catch(()=>undefined);setSelectedDate(shiftCalendarMonth(selectedDate,delta))}
 async function jumpToday(){void Haptics.selectionAsync().catch(()=>undefined);setSelectedDate(null);setMode('Day')}
 return <NeverScreen style={[styles.safe,{backgroundColor:p.canvas}]} edges={['top','left','right']}><ScrollView contentContainerStyle={[styles.content,p.pageStyle]} showsVerticalScrollIndicator={false}>
  <Pass3ScreenIntro eyebrow="Time" title="Calendar" body="Dates and plans surfaced from your memory." trailing={selectedDate!==today?<Pass3TextAction label="Today" onPress={()=>void jumpToday()}/>:undefined}/>
  <View style={styles.dateStage}>
   <View style={styles.dateHero}><View><Text style={[styles.dateNumber,{color:p.label}]}>{selected.getDate()}</Text><Text style={[styles.dateWeekday,{color:p.secondary}]}>{weekdayName}</Text></View><View style={styles.dateMeta}><Text style={[styles.monthTitle,{color:p.label}]}>{monthName}</Text><Text style={[styles.yearText,{color:p.tertiary}]}>{selected.getFullYear()} · {selectedItems.length} {selectedItems.length===1?'item':'items'}</Text></View></View>
   <View style={[styles.monthControls,{borderTopColor:p.separator,borderBottomColor:p.separator}]}><MonthArrow left onPress={()=>void moveMonth(-1)}/><Text style={[styles.monthControlLabel,{color:p.secondary}]}>{monthName} {selected.getFullYear()}</Text><MonthArrow onPress={()=>void moveMonth(1)}/></View>
   <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.dayStrip}>{strip.map((day)=>{const active=day.iso===selectedDate;const hasItems=datedItems.some((item)=>item.date===day.iso);return <Pressable accessibilityRole="button" accessibilityLabel={prettyGroupDate(day.iso)} accessibilityState={{selected:active}} key={day.iso} onPress={()=>{void Haptics.selectionAsync().catch(()=>undefined);setSelectedDate(day.iso)}} style={({pressed})=>[styles.day,{opacity:pressed?.55:1}]}><Text style={[styles.weekday,{color:active?p.label:p.tertiary}]}>{day.weekday}</Text><View style={[styles.dayNumberWrap,{borderRadius:p.radius.chip,backgroundColor:active?p.graphite:'transparent',borderColor:active?p.graphite:p.border}]}><Text style={[styles.dayNumberSmall,{color:active?p.onAccent:p.label}]}>{day.number}</Text></View><View style={[styles.dot,{backgroundColor:hasItems?p.chrome:'transparent'}]}/></Pressable>})}</ScrollView>
   <V5Segmented options={['Day','Week','Month']} selected={mode} onSelect={(value)=>setMode(value as CalendarMode)}/>
  </View>
  {mode==='Day'?<><AgendaSection title={selectedDate===today?'Today':weekdayName} items={selectedItems} emptyTitle="No plans here" emptyBody="Capture something with a date and it will appear here."/><AgendaSection title={selectedDate===today?'Tomorrow':prettyNextLabel(nextDate)} items={nextItems} emptyTitle="Nothing ahead" emptyBody="The next day is clear."/></>:<Pass3Section title={mode==='Week'?'This week':monthName} meta={`${visibleItems.length}`}>{grouped.length?grouped.map((group)=><View key={group.date} style={styles.groupBlock}><Text style={[styles.dateLabel,{color:p.tertiary}]}>{prettyGroupDate(group.date)}</Text><AgendaRows items={group.items}/></View>):<EmptyAgenda title="Nothing scheduled" body="Your schedule is clear for this view."/>}</Pass3Section>}
 </ScrollView></NeverScreen>
}

function MonthArrow({left=false,onPress}:{left?:boolean;onPress:()=>void}){const p=useNeverV5Palette();return <Pressable accessibilityRole="button" accessibilityLabel={left?'Previous month':'Next month'} onPress={onPress} style={({pressed})=>[styles.monthArrow,{backgroundColor:pressed?p.fillSoft:'transparent',borderRadius:p.radius.icon}]}><OneIcon name={left?icons.chevronLeft:icons.chevron} size={14} color={p.chrome}/></Pressable>}
function AgendaSection({title,items,emptyTitle,emptyBody}:{title:string;items:OneItem[];emptyTitle:string;emptyBody:string}){return <Pass3Section title={title} meta={`${items.length}`}>{items.length?<AgendaRows items={items}/>:<EmptyAgenda title={emptyTitle} body={emptyBody}/>}</Pass3Section>}
function AgendaRows({items}:{items:OneItem[]}){const p=useNeverV5Palette();return <View style={[styles.agendaRows,{borderTopColor:p.separator,borderBottomColor:p.separator}]}>{items.map((item,index)=><View key={item.id}><AgendaRow item={item}/>{index<items.length-1?<Pass3Divider/>:null}</View>)}</View>}
function AgendaRow({item}:{item:OneItem}){const p=useNeverV5Palette();return <Pressable accessibilityRole="button" onPress={()=>router.push({pathname:'/item/[id]',params:{id:item.id}})} style={({pressed})=>[styles.agendaRow,{backgroundColor:pressed?p.fillSoft:'transparent'}]}><View style={styles.timeColumn}><Text style={[styles.time,{color:p.chrome}]}>{item.time||'Any'}</Text></View><View style={styles.agendaCopy}><Text style={[styles.itemTitle,{color:p.label}]} numberOfLines={2}>{item.title}</Text><Text style={[styles.itemMeta,{color:p.secondary}]} numberOfLines={1}>{[item.location,item.summary,item.category].filter(Boolean).join(' · ')||item.type}</Text></View><V5Chevron/></Pressable>}
function EmptyAgenda({title,body}:{title:string;body:string}){const p=useNeverV5Palette();return <View style={[styles.emptyRow,{borderTopColor:p.separator,borderBottomColor:p.separator}]}><OneIcon name={icons.calendar} size={17} color={p.chrome}/><View style={{flex:1}}><Text style={[styles.emptyTitle,{color:p.label}]}>{title}</Text><Text style={[styles.emptyBody,{color:p.secondary}]}>{body}</Text></View></View>}
function filterForMode(items:OneItem[],selectedDate:string,mode:CalendarMode){if(mode==='Day')return items.filter((item)=>item.date===selectedDate);const selected=new Date(`${selectedDate}T12:00:00`);if(mode==='Week'){const day=selected.getDay();const mondayOffset=day===0?-6:1-day;const start=new Date(selected);start.setDate(selected.getDate()+mondayOffset);const end=new Date(start);end.setDate(start.getDate()+6);const startIso=toIsoDate(start);const endIso=toIsoDate(end);return items.filter((item)=>item.date&&item.date>=startIso&&item.date<=endIso)}const prefix=selectedDate.slice(0,7);return items.filter((item)=>item.date?.startsWith(prefix))}
function groupByDate(items:OneItem[]){const map=new Map<string,OneItem[]>();for(const item of items){if(!item.date)continue;const group=map.get(item.date)||[];group.push(item);map.set(item.date,group)}return Array.from(map.entries()).map(([date,groupedItems])=>({date,items:groupedItems}))}
function prettyGroupDate(iso:string){return new Intl.DateTimeFormat('en',{weekday:'short',month:'short',day:'numeric'}).format(new Date(`${iso}T12:00:00`))}
function prettyNextLabel(iso:string){return new Intl.DateTimeFormat('en',{weekday:'long'}).format(new Date(`${iso}T12:00:00`))}
function addDaysIso(iso:string,days:number){const date=new Date(`${iso}T12:00:00`);date.setDate(date.getDate()+days);return toIsoDate(date)}
function getDays(center:Date,count:number){const start=new Date(center);start.setDate(center.getDate()-3);return Array.from({length:count},(_,index)=>{const date=new Date(start);date.setDate(start.getDate()+index);return{iso:toIsoDate(date),weekday:new Intl.DateTimeFormat('en',{weekday:'short'}).format(date).slice(0,2).toUpperCase(),number:date.getDate()}})}
function toIsoDate(date:Date){const y=date.getFullYear();const m=String(date.getMonth()+1).padStart(2,'0');const d=String(date.getDate()).padStart(2,'0');return`${y}-${m}-${d}`}

const styles=StyleSheet.create({safe:{flex:1},content:{width:'100%',maxWidth:760,alignSelf:'center',paddingHorizontal:20,paddingTop:18,paddingBottom:126},dateStage:{gap:14},dateHero:{minHeight:92,flexDirection:'row',alignItems:'center',gap:20,paddingHorizontal:2},dateNumber:{fontSize:58,lineHeight:60,fontWeight:'300',letterSpacing:-2.6},dateWeekday:{fontSize:12,lineHeight:16,fontWeight:'600'},dateMeta:{flex:1},monthTitle:{fontSize:24,lineHeight:28,fontWeight:'600',letterSpacing:-.55},yearText:{marginTop:3,fontSize:11.5,lineHeight:15},monthControls:{minHeight:48,borderTopWidth:StyleSheet.hairlineWidth,borderBottomWidth:StyleSheet.hairlineWidth,flexDirection:'row',alignItems:'center'},monthArrow:{width:44,height:44,alignItems:'center',justifyContent:'center'},monthControlLabel:{flex:1,textAlign:'center',fontSize:12,lineHeight:16,fontWeight:'600'},dayStrip:{flexGrow:1,flexDirection:'row',justifyContent:'space-between',gap:4,paddingVertical:2},day:{minWidth:44,alignItems:'center'},weekday:{fontSize:9.5,lineHeight:12,fontWeight:'700',letterSpacing:.25},dayNumberWrap:{minWidth:36,minHeight:36,padding:6,marginTop:5,borderWidth:StyleSheet.hairlineWidth,alignItems:'center',justifyContent:'center'},dayNumberSmall:{fontSize:14.5,lineHeight:18,fontWeight:'600'},dot:{width:4,height:4,borderRadius:2,marginTop:4},groupBlock:{gap:7,marginBottom:18},dateLabel:{paddingHorizontal:2,fontSize:11.5,lineHeight:14,fontWeight:'600'},agendaRows:{borderTopWidth:StyleSheet.hairlineWidth,borderBottomWidth:StyleSheet.hairlineWidth},agendaRow:{minHeight:70,paddingHorizontal:8,flexDirection:'row',alignItems:'center',gap:12},timeColumn:{width:48,alignItems:'flex-start'},time:{fontSize:11.5,lineHeight:15,fontWeight:'700'},agendaCopy:{flex:1,minWidth:0},itemTitle:{fontSize:15.5,lineHeight:19,fontWeight:'600'},itemMeta:{marginTop:2,fontSize:12.5,lineHeight:16},emptyRow:{minHeight:82,paddingHorizontal:8,borderTopWidth:StyleSheet.hairlineWidth,borderBottomWidth:StyleSheet.hairlineWidth,flexDirection:'row',alignItems:'center',gap:12},emptyTitle:{fontSize:14.5,lineHeight:18,fontWeight:'600'},emptyBody:{marginTop:2,fontSize:12.5,lineHeight:16}});
