export type OneTheme = {
  background: string;
  surface: string;
  surfaceElevated: string;
  fill: string;
  fillStrong: string;
  text: string;
  textSecondary: string;
  textTertiary: string;
  border: string;
  accent: string;
  accentSoft: string;
  onAccent: string;
  chrome: string;
  chromeSoft: string;
  platinum: string;
  platinumSoft: string;
  glass: string;
  glassStrong: string;
  glassBorder: string;
  reflection: string;
  shadow: string;
  success: string;
  successSoft: string;
  danger: string;
  dangerSoft: string;
  warning: string;
  warningSoft: string;
  sky: string;
  skySoft: string;
  plum: string;
  plumSoft: string;
};

// Canonical NEVER materials. All compatibility palettes derive from these tokens.
export const lightTheme: OneTheme = {
  background: '#E6E9EC',
  surface: '#F4F6F7',
  surfaceElevated: '#FCFDFD',
  fill: '#E0E5E9',
  fillStrong: '#C8D0D6',
  text: '#171D22',
  textSecondary: '#5E6872',
  textTertiary: '#5F6A74',
  border: '#CDD4DA',
  accent: '#313B45',
  accentSoft: '#DFE5EA',
  onAccent: '#FBFCFD',
  chrome: '#667684',
  chromeSoft: '#DEE4E8',
  platinum: '#9AA7B1',
  platinumSoft: '#EEF1F3',
  glass: '#F8FAFBD6',
  glassStrong: '#F3F6F8EE',
  glassBorder: '#FFFFFFF2',
  reflection: '#FFFFFFE0',
  shadow: '#26333E',
  success: '#28734D',
  successSoft: '#E3EFE7',
  danger: '#B43C3C',
  dangerSoft: '#F7E8E7',
  warning: '#876020',
  warningSoft: '#F2EBD9',
  sky: '#667684',
  skySoft: '#DEE4E8',
  plum: '#696372',
  plumSoft: '#EDEBF0'
};

export const darkTheme: OneTheme = {
  background: '#11161B',
  surface: '#1C232A',
  surfaceElevated: '#252E36',
  fill: '#2A333C',
  fillStrong: '#3B4651',
  text: '#F4F6F7',
  textSecondary: '#B8C1C8',
  textTertiary: '#8F9BA5',
  border: '#333E48',
  accent: '#DCE4EA',
  accentSoft: '#2D3740',
  onAccent: '#172028',
  chrome: '#C4D0D8',
  chromeSoft: '#313C46',
  platinum: '#AAB8C3',
  platinumSoft: '#252E36',
  glass: '#222B33DC',
  glassStrong: '#202830F2',
  glassBorder: '#FFFFFF20',
  reflection: '#FFFFFF16',
  shadow: '#05080B',
  success: '#8DC9A8',
  successSoft: '#253D31',
  danger: '#F49A94',
  dangerSoft: '#462E32',
  warning: '#DDBA7C',
  warningSoft: '#3D3628',
  sky: '#C4D0D8',
  skySoft: '#313C46',
  plum: '#C0B9CA',
  plumSoft: '#36323E'
};
